[tool.poetry]
name = "orquestrador-mage-ai"
version = "0.1.0"
description = ""
authors = ["Renan Marx <renan.marx@distrito.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
